/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        bg: 'var(--notion-bg)',
        'bg-alt': 'var(--notion-bg-alt)',
        surface: 'var(--notion-surface)',
        text: {
          DEFAULT: 'var(--notion-text)',
          secondary: 'var(--notion-text-secondary)',
          muted: 'var(--notion-text-muted)',
        },
        border: 'var(--notion-border)',
        blue: {
          DEFAULT: 'var(--notion-blue)',
          hover: 'var(--notion-blue-hover)',
          focus: 'var(--notion-blue-focus)',
        },
        badge: {
          bg: 'var(--notion-badge-bg)',
          text: 'var(--notion-badge-text)',
        },
        teal: 'var(--notion-teal)',
        green: 'var(--notion-green)',
        orange: 'var(--notion-orange)',
        pink: 'var(--notion-pink)',
        purple: 'var(--notion-purple)',
        brown: 'var(--notion-brown)',
        /* shadcn compat — keep these so existing bg-background/text-foreground/etc still work */
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'system-ui', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['4.00rem', { lineHeight: '1.00', letterSpacing: '-2.125px', fontWeight: '700' }],
        'display-2':    ['3.38rem', { lineHeight: '1.04', letterSpacing: '-1.875px', fontWeight: '700' }],
        'section':      ['3.00rem', { lineHeight: '1.00', letterSpacing: '-1.5px',   fontWeight: '700' }],
        'sub-lg':       ['2.50rem', { lineHeight: '1.50', letterSpacing: 'normal',   fontWeight: '700' }],
        'sub':          ['1.63rem', { lineHeight: '1.23', letterSpacing: '-0.625px', fontWeight: '700' }],
        'card-title':   ['1.38rem', { lineHeight: '1.27', letterSpacing: '-0.25px',  fontWeight: '700' }],
        'body-lg':      ['1.25rem', { lineHeight: '1.40', letterSpacing: '-0.125px', fontWeight: '600' }],
        'nav':          ['0.94rem', { lineHeight: '1.33', letterSpacing: 'normal',   fontWeight: '600' }],
        'caption':      ['0.88rem', { lineHeight: '1.43', letterSpacing: 'normal',   fontWeight: '500' }],
        'badge-text':   ['0.75rem', { lineHeight: '1.33', letterSpacing: '0.125px',  fontWeight: '600' }],
      },
      borderRadius: {
        micro: '4px',
        subtle: '5px',
        standard: '8px',
        comfortable: '12px',
        large: '16px',
        pill: '9999px',
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        deep: 'var(--shadow-deep)',
        focus: '0 0 0 2px var(--notion-blue-focus)',
      },
    },
  },
  plugins: [],
};
